import type { CollectionConfig } from 'payload'

import { isSelfOrAdmin } from '../access/isSelfOrAdmin'
import { admins } from '../access/admins'

export const RegistryForms: CollectionConfig = {
  labels: {
    singular: 'Registry Form',
    plural: 'Registry Forms',
  },
  slug: 'registry-forms',
  access: {
    read: isSelfOrAdmin,
    create: isSelfOrAdmin,
    delete: isSelfOrAdmin,
    update: admins,
  },
  fields: [
    {
      name: 'registry_status',
      label: 'Registry Status',
      type: 'select',
      options: [
        {
          label: 'Approved',
          value: 'approved',
        },
        {
          label: 'In Review',
          value: 'review',
        },
      ],
      defaultValue: 'review',
      hasMany: false,
      required: false,
    },
    {
      name: 'user_id',
      label: 'User ID',
      type: 'text',
      required: true,
      access: {
        update: () => false,
      },
    },
    {
      name: 'first_name',
      label: 'First Name',
      type: 'text',
      required: true,
    },
    {
      name: 'last_name',
      label: 'Last Name',
      type: 'text',
      required: true,
    },
    {
      name: 'email',
      type: 'email',
      unique: true,
      required: true,
    },
    {
      name: 'primary_phone_number',
      label: 'Primary Phone Number',
      type: 'text',
      required: true,
    },
    {
      label: 'Preferred Contact Method',
      name: 'preferred_contact_method',
      type: 'radio',
      options: [
        { label: 'By email', value: 'email' },
        { label: 'By phone', value: 'phone' },
      ],
      required: true,
    },
    {
      label: 'Languages',
      name: 'languages',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'English', value: 'en' },
        { label: 'Français', value: 'fr' },
        { label: '简体中文', value: 'zh' },
        { label: 'Tiếng Việt', value: 'vn' },
        { label: 'ᜆᜄᜎᜓᜄ᜔', value: 'tl' },
        { label: 'ភាសាខ្មែរ', value: 'km' },
        { label: '日本語', value: 'ja' },
        { label: '한국어', value: 'ko' },
      ],
      required: true,
    },
    {
      label: 'Other Languages',
      name: 'other_languages',
      type: 'text',
      required: false,
    },
    {
      label: 'Status',
      name: 'status',
      type: 'radio',
      options: [
        {
          label: 'Studying',
          value: 'student',
        },
        {
          label: 'Seeking employment',
          value: 'unemployed',
        },
        {
          label: 'Employed',
          value: 'employed',
        },
      ],
      required: true,
    },
    {
      name: 'estimated graduation date',
      type: 'date',
      required: false,
    },
    {
      name: 'profession',
      type: 'select',
      options: [
        { label: 'Acupuncturist', value: 'acupuncturist' },
        { label: 'Anesthesiologist', value: 'anesthesiologist' },
        { label: 'Audiologist', value: 'audiologist' },
        { label: 'Chiropractor', value: 'chiropractor' },
        { label: 'Clinical Psychologist', value: 'clinical_psychologist' },
        { label: 'Dentist', value: 'dentist' },
        { label: 'Dermatologist', value: 'dermatologist' },
        { label: 'Dietitian', value: 'dietitian' },
        {
          label: 'Emergency Medicine Physician',
          value: 'emergency_medicine_physician',
        },
        { label: 'Endocrinologist', value: 'endocrinologist' },
        { label: 'Family Medicine Physician', value: 'family_medicine_physician' },
        { label: 'Gastroenterologist', value: 'gastroenterologist' },
        { label: 'General Practitioner', value: 'general_practitioner' },
        { label: 'Gynecologist', value: 'gynecologist' },
        { label: 'Hearing Specialist', value: 'hearing_specialist' },
        { label: 'Homeopath', value: 'homeopath' },
        {
          label: 'Internal Medicine Physician',
          value: 'internal_medicine_physician',
        },
        { label: 'Massage Therapist', value: 'massage_therapist' },
        { label: 'Naturopath', value: 'naturopath' },
        { label: 'Neurologist', value: 'neurologist' },
        { label: 'Nurse Practitioner', value: 'nurse_practitioner' },
        { label: 'Obstetrician', value: 'obstetrician' },
        { label: 'Occupational Therapist', value: 'occupational_therapist' },
        { label: 'Oncologist', value: 'oncologist' },
        { label: 'Ophthalmologist', value: 'ophthalmologist' },
        { label: 'Optometrist', value: 'optometrist' },
        { label: 'Orthopedic Surgeon', value: 'orthopedic_surgeon' },
        { label: 'Osteopath', value: 'osteopath' },
        { label: 'Pain Management Specialist', value: 'pain_management_specialist' },
        { label: 'Pediatrician', value: 'pediatrician' },
        { label: 'Podiatrist', value: 'podiatrist' },
        { label: 'Plastic Surgeon', value: 'plastic_surgeon' },
        { label: 'Podiatric Surgeon', value: 'podiatric_surgeon' },
        { label: 'Psychiatrist', value: 'psychiatrist' },
        { label: 'Psychologist', value: 'psychologist' },
        { label: 'Pulmonologist', value: 'pulmonologist' },
        { label: 'Radiologist', value: 'radiologist' },
        {
          label: 'Reproductive Endocrinologist',
          value: 'reproductive_endocrinologist',
        },
        { label: 'Rheumatologist', value: 'rheumatologist' },
        { label: 'Sleep Specialist', value: 'sleep_specialist' },
        {
          label: 'Speech-Language Pathologist',
          value: 'speech_language_pathologist',
        },
        { label: 'Sports Medicine Physician', value: 'sports_medicine_physician' },
        { label: 'Surgical Specialist', value: 'surgical_specialist' },
        { label: 'Urologist', value: 'urologist' },
        { label: 'Vascular Surgeon', value: 'vascular_surgeon' },
        { label: 'Wound Care Specialist', value: 'wound_care_specialist' },
        { label: 'Wellness Coach', value: 'wellness_coach' },
        { label: 'Yoga Therapist', value: 'yoga_therapist' },
        { label: 'Orthodontist', value: 'orthodontist' },
        { label: 'Palliative Care Specialist', value: 'palliative_care_specialist' },
        { label: 'Chronic Pain Specialist', value: 'chronic_pain_specialist' },
        { label: 'Biofeedback Specialist', value: 'biofeedback_specialist' },
        { label: 'Nutritionist', value: 'nutritionist' },
        { label: 'Other profession', value: 'other' },
      ],
      required: true,
    },
    {
      name: 'other profession',
      type: 'text',
      required: false,
    },
    {
      name: 'sectors',
      type: 'select',
      options: [
        {
          label: 'Public',
          value: 'public',
        },
        {
          label: 'Private',
          value: 'private',
        },
      ],
      hasMany: true,
      required: false,
    },
  ],
}
