import { Header } from '@/components/Header'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import TranslationProvider from '@/components/providers/TranslationProvider'
import { getTranslations } from '@/lib/get-translations'
import { cn } from '@/lib/utils'
import { i18n, Locale } from '@/translations/i18n-config'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'YAHPA v2 - Demo',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout(props: {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}) {
  const params = await props.params

  const t = await getTranslations(params.lang)

  return (
    <html lang={params.lang} suppressHydrationWarning>
      <head />
      <body className={cn([inter.className, 'flex', 'min-h-screen', 'flex-col'])}>
        <TranslationProvider translation={t} currentLocale={params.lang}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header t={t} />
            <div className="flex flex-1">
              <main className="flex-1">{props.children}</main>
            </div>
            <footer className="flex flex-col items-center justify-center p-4 bg-neutral-900">
              <span className="mb-2 text-white">{t.footer.rights}</span>

              <Link href="/admin" className="text-sm text-white hover:underline">
                {t.footer.admin}
              </Link>
            </footer>
          </ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  )
}
