import { Header } from '@/components/Header'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn([inter.className, 'flex', 'min-h-screen', 'flex-col'])}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="flex flex-1">
            <main className="flex-1">{children}</main>
          </div>
          <footer className="flex flex-col items-center justify-center p-4 bg-neutral-900">
            <span className="mb-2 text-white">All rights deserved YAHPA © 2021</span>

            <Link href="/admin" className="text-sm text-white hover:underline">
              Admin Portal
            </Link>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
